update

diff --git a/load_balancer/0-custom_http_response_header b/load_balancer/0-custom_http_response_header
--- a/load_balancer/0-custom_http_response_header
+++ b/load_balancer/0-custom_http_response_header
@@ -1,49 +1,84 @@
 #!/usr/bin/env bash
-# installing and config nginx
+# duplicate web-01 to web-02
+# these scripts are an upgrade from the web-server scripts...
 
-apt-get update
-apt-get -y install nginx
+# uncomment to see the script run in action
+#set -x
 
-# adding a html page
-echo "Holberton School" > /var/www/html/index.html
-echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
+echo -e "Updating and doing some minor checks...\n"
 
-CONFIG=\
+function install() {
+	command -v "$1" &> /dev/null
+
+	#shellcheck disable=SC2181
+	if [ $? -ne 0 ]; then
+		echo -e "	Installing: $1$\n"
+		sudo apt-get update -y -qq && \
+			sudo apt-get install -y "$1" -qq
+		echo -e "\n"
+	else
+		echo -e "	${1} is already installed.\n"
+	fi
+}
+
+install nginx #install nginx
+
+echo -e "\nSetting up some minor stuff.\n"
+
+# allowing nginx on firewall
+sudo ufw allow 'Nginx HTTP'
+
+# Give the user ownership to website files for easy editing
+if [ -d "/var/www" ]; then
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+else
+	sudo mkdir -p /var/www
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+fi
+
+# create directories if not present
+for dir in /var/www/{html,error}; do
+	if ! [ -d "$dir" ]; then
+		mkdir -p "$dir"
+	fi
+done
+
+# creating new index
+echo "Hello World!" > /var/www/html/index.html
+
+# create new error page
+echo "Ceci n'est pas une page" > /var/www/html/error_404.html
+
+# backup default server config file
+sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
+
+server_config=\
 "server {
-	listen 80 default_server;
-  	listen [::]:80 default_server;
-
-        root /var/www/html;
-
-        index index.html index.htm index.nginx-debian.html;
-
-	error_page 404 /custom_404.html;
-
-	server_name _;
-
-	rewrite ^/redirect_me(.*)$ http://www.google.com/ permanent;
-
-	location = /custom_404.html {
-		root /usr/share/nginx/html;
-		internal;
-	}
-
-        location / {
-                try_files \$uri \$uri/ =404;
-	}
-	add_header X-Served-By \$hostname;
+		listen 80 default_server;
+		listen [::]:80 default_server;
+		root /var/www/html;
+		index index.html index.htm index.nginx-debian.html
+		server_name_;
+		add_header X-Served-By \$hostname;
+		location / {
+			try_files \$uri \$uri/ =404;
+		}
+		if (\$request_filename ~ redirect_me){
+			rewrite ^ https://th3-gr00t.tk/ permanent;
+		}
+		error_page 404 /error_404.html;
+		location = /error_404.html {
+			internal;
+		}
 }"
 
-echo -e "$CONFIG" > /etc/nginx/sites-enabled/default
+#shellcheck disable=SC2154
+echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
 
-# checking if service is running
-state=$(pgrep nginx)
-if [ -n "$state" ];
-then
-	sudo service nginx restart
-	echo "resarting Nginx...."
-else
+if [ "$(pgrep -c nginx)" -le 0 ]; then
 	sudo service nginx start
-	echo "Ngix started.."
+else
+	sudo service nginx restart
 fi
-echo "done"
