update

diff --git a/web_server/0-transfer_file b/web_server/0-transfer_file
--- a/web_server/0-transfer_file
+++ b/web_server/0-transfer_file
@@ -1,9 +1,18 @@
 #!/usr/bin/env bash
-# script that copy a file to a remoteserver
-
-if [ $# -lt 4 ]
-then
-	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-	exit
+#Transfering a file to your server
+if [ "$#" -ne 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
 fi
-scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
+file_path=$1
+server_ip=$2
+username=$3
+ssh_key=$4
+
+scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip":~/
+
+f [ $? -eq 0 ]; then
+    echo "Check file transfered successful!"
+else
+    echo "File transfer failed."
+fi 
diff --git a/web_server/1-install_nginx_web_server b/web_server/1-install_nginx_web_server
--- a/web_server/1-install_nginx_web_server
+++ b/web_server/1-install_nginx_web_server
@@ -1,8 +1,22 @@
 #!/usr/bin/env bash
-#install nginx and redirects to holberton school string
-
-sudo apt-get -y update
-sudo apt-get -y install nginx
-file1=/usr/share/nginx/html/index.html
-sudo bash -c "echo 'Holberton School ftw!' > $file1"
-service nginx start
+# install nginx and config
+# update package list
+sudo apt-get update || { echo "Failed to update package list"; exit 1; }
+# install nginx
+sudo apt-get install -y nginx || { echo "Failed to install Nginx"; exit 1; }
+# run it
+sudo service nginx start || { echo "Failed to start Nginx"; exit 1; }
+# create a custom HTML page
+echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null
+# configure nginx (port 80)
+sudo sed -i '/listen 80 default_server/ s/80 default_server/80 default_server ipv6only=on/' /etc/nginx/sites-available/default || { echo "Failed to configure Nginx"; exit 1; }
+# restart nginx
+sudo service nginx restart || { echo "Failed to restart Nginx"; exit 1; }
+sleep 2
+# if it returns the expectation
+curl_output=$(curl -s http://localhost)
+if [[ "$curl_output" == *"Holberton School"* ]]; then
+    echo "Nginx configured successfully!"
+else
+    echo "Nginx configuration check failed."
+fi
